"""
Naive Mandelbrot set generator.

Implements the steps from the assignment:
 - mandelbrot_point: iteration count for a single complex number
 - mandelbrot_grid: compute a 2D grid of iteration counts using nested loops
 - timing of a 1024x1024 grid
 - visualization with matplotlib
"""

import time
import numpy as np
import matplotlib.pyplot as plt
import statistics

from mandelbrot_naive import plot_mandelbrot


# this whole code was generated by generative ai, i have not modified it yet

def mandelbrot_point(c: complex, max_iter: int = 80) -> int:
    """
    Step 2: Mandelbrot for a single point.

    Parameters
    ----------
    c : complex
        Complex parameter for the iteration z_{n+1} = z_n^2 + c.
    max_iter : int
        Maximum number of iterations.

    Returns
    -------
    int
        Iteration count until escape; returns max_iter if it never escapes
        (e.g. c = 0).
    """
    z = 0 + 0j
    for n in range(max_iter):
        z = z * z + c
        if (z.real * z.real + z.imag * z.imag) > 4.0:
            return n
    return max_iter


def mandelbrot_numpy(
    xmin: float = -2.0,
    xmax: float = 1.0,
    ymin: float = -1.5,
    ymax: float = 1.5,
    width: int = 100,
    height: int = 100,
    max_iter: int = 80,
) -> np.ndarray:
    """
    Step 3: Compute Mandelbrot set on a grid using nested loops.

    Creates a mesh of complex numbers and calls mandelbrot_point for each.

    Returns
    -------
    np.ndarray
        2D array of iteration counts with shape (height, width).
    """
    # Complex grid
    x = np.linspace(xmin, xmax, width)
    y = np.linspace(ymin, ymax, height)
    X, Y = np.meshgrid(x, y)
    C = X + 1j * Y

    Z = np.zeros_like(C)
    iters = np.zeros(C.shape, dtype=np.int32)
    mask = np.ones(C.shape, dtype=bool)   # points still evolving

    for n in range(max_iter):
        Z[mask] = Z[mask] * Z[mask] + C[mask]
        escaped = np.abs(Z) > 2.0         # points that just escaped
        newly_escaped = escaped & mask
        iters[newly_escaped] = n
        mask &= ~escaped                  # stop updating escaped points
        if not mask.any():
            break

    # Points that never escaped keep iters = 0; optionally set to max_iter
    iters[mask] = max_iter
    return iters


def sum_row(N, A):
    t0 = time.perf_counter()
    for i in range(N):
        rs = np.sum(A[i, :])
    t1 = time.perf_counter()
    return t1 - t0

def sum_column(N, A):
    t0 = time.perf_counter()
    for i in range(N):
        rs = np.sum(A[:, i])
    t1 = time.perf_counter()
    return t1 - t0


def memory_access_pattern():
    N = 100
    A = np.random.rand(N, N)
    A_f = np.asfortranarray(A)
    time1 = sum_row(N, A)
    time2 = sum_column(N, A)
    print(f"row wise computation took :{time1}" )
    print(f"sum wise computation took :{time2}" )


    timeA_f1 = sum_row(N,A_f)
    timeA_f2 = sum_column(N,A_f)
    print(f"row wise computation took for fortran:{timeA_f1}" )
    print(f"row wise computation took for fortran:{timeA_f2}" )




def benchmark_numpy(width,height,max_iter):
        print(f"Computing Mandelbrot grid {width}x{height} (no NumPy) ...")
        t0 = time.perf_counter()
        grid = mandelbrot_numpy(width=width, height=height, max_iter=max_iter)

        perfomance_list = []
        # Compute max iteration by scanning the list-of-lists
        for _ in range(3):
            t1 = time.perf_counter()
            elapsed = (t1 - t0) 
            perfomance_list.append(elapsed)
        median_time = statistics.median(perfomance_list)
        print(f"Computation took {elapsed:.3f} seconds for naive implementation")     
        return median_time,grid


if __name__ == "__main__":
    # Step 2: quick sanity checks for mandelbrot_point
    max_iter = 80
    # change this to True to show different visualizations
    showDifferentVisualizations = False
    perfomance_list = []

    # Step 3–4: compute a grid and measure time
    width, height = 1024, 1024
    print(f"Computing Mandelbrot grid {width}x{height} ...")

    t,grid = benchmark_numpy(width,height,max_iter)



    for cmap in ["hot", "viridis", "twilight"]:
        plot_mandelbrot(
            grid,
            xmin=-2.0,
            xmax=1.0,
            ymin=-1.5,
            ymax=1.5,
            cmap=cmap,
            filename=f"mandelbrot_no_numpy_{cmap}.png",
        )

  
    memory_access_pattern()



   

